apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  labels:
    app: session-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
        version: v2  # ← Новая версия
    spec:
      containers:
      - name: session-service
        image: session-service:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: jwt-keys
